# Generated by Django 3.1.7 on 2021-08-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210813_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('expire_date', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ['-date']},
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['ip_address'], name='account_ipa_ip_addr_4cbb03_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date'], name='account_use_date_1edf1a_idx'),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['expire_date'], name='account_cod_expire__2ccc13_idx'),
        ),
    ]
