# Generated by Django 3.2.7 on 2021-09-07 07:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='code',
            managers=[
                ('ohjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
