# Generated by Django 3.2.8 on 2021-10-24 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20211023_0841'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='code',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='code_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
