# Generated by Django 3.2.5 on 2021-08-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-date']},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['episode'], name='podcast_com_episode_07f3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='podcast_com_user_id_5ad53b_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['podcast'], name='podcast_epi_podcast_244434_idx'),
        ),
    ]
