# Generated by Django 3.1.7 on 2021-08-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_episode_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
